name: finalproj_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  go_router: ^14.1.3
  url_strategy: ^0.2.0

  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  firebase_core: ^2.31.0
  google_fonts:
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.1
  path: ^1.9.0


  user_repository:
    path: packages/user_repository
  recipe_repository:
    path: packages/recipe_repository



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
 uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 