name: finalproj
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  # firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  image_cropper: ^6.0.0
  image_picker: ^1.1.1
  # rxdart: ^0.27.7
  # path: ^1.9.0
  image_cropper_for_web: ^4.0.0
  fastor_app_ui_widget: ^1.3.61
  get: ^4.6.6
  get_storage: ^2.1.1
  
  

  user_repository:
    path: packages/user_repository

  recipe_repository:
    path: packages/recipe_repository



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  
  assets:
    - lib/images/


