// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGl5Szl81R2kE5cE5rg4BPc0go7QScsdY',
    appId: '1:465698101894:web:8fbcf3e53c17fdad628f07',
    messagingSenderId: '465698101894',
    projectId: 'koyam-recette',
    authDomain: 'koyam-recette.firebaseapp.com',
    storageBucket: 'koyam-recette.appspot.com',
    measurementId: 'G-BZ0J8GVL94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtQGlj_reTMakHJgH2JPysOdyqiX0Lp_8',
    appId: '1:465698101894:android:902806aff5fc2951628f07',
    messagingSenderId: '465698101894',
    projectId: 'koyam-recette',
    storageBucket: 'koyam-recette.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0wXAwvZhyPFEr6Yowi8MIJHjSNS9wujg',
    appId: '1:465698101894:ios:fbe22682e4371e3c628f07',
    messagingSenderId: '465698101894',
    projectId: 'koyam-recette',
    storageBucket: 'koyam-recette.appspot.com',
    iosBundleId: 'com.example.finalproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0wXAwvZhyPFEr6Yowi8MIJHjSNS9wujg',
    appId: '1:465698101894:ios:fbe22682e4371e3c628f07',
    messagingSenderId: '465698101894',
    projectId: 'koyam-recette',
    storageBucket: 'koyam-recette.appspot.com',
    iosBundleId: 'com.example.finalproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGl5Szl81R2kE5cE5rg4BPc0go7QScsdY',
    appId: '1:465698101894:web:d1b9fd3e813e5b0d628f07',
    messagingSenderId: '465698101894',
    projectId: 'koyam-recette',
    authDomain: 'koyam-recette.firebaseapp.com',
    storageBucket: 'koyam-recette.appspot.com',
    measurementId: 'G-JEDDMHCFVJ',
  );

}